name: With Regard
markdown: redcarpet
pygments: true

authors:
  neil:
    display_name: Neil Anderson
    gravatar: 60fd5218fff6927c0ed376cce01c5460
    email: neil@withregard.io
    twitter: NeilAnders0n
    github: eneiand